In [18]:
##### データの読み込み #####
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv('/Users/ryosuke/ai-engneering/dataset/mayonnaise/demand_forecasting.csv')

In [19]:
##### データの中身の確認 #####
df.head(20)

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59
5,2022-01-01,S001,P0006,Toys,North,209,60,0,35.53,0,Snowy,0,40.01,Winter,0,55
6,2022-01-01,S001,P0007,Groceries,North,118,81,335,23.27,5,Snowy,0,24.78,Winter,0,94
7,2022-01-01,S001,P0008,Electronics,North,244,42,0,37.79,5,Snowy,0,44.85,Winter,0,61
8,2022-01-01,S001,P0009,Clothing,North,115,88,139,94.20,5,Snowy,0,108.70,Winter,0,129
9,2022-01-01,S001,P0010,Furniture,North,192,70,300,113.35,10,Snowy,0,129.98,Winter,0,69
10,2022-01-01,S001,P0011,Furniture,North,215,51,142,156.34,0,Snowy,0,188.96,Winter,0,64
11,2022-01-01,S001,P0012,Groceries,North,289,121,215,84.48,0,Snowy,0,92.02,Winter,0,104
12,2022-01-01,S001,P0013,Toys,North,279,113,0,33.10,5,Snowy,0,39.11,Winter,0,110
13,2022-01-01,S001,P0014,Groceries,North,252,121,479,80.13,10,Snowy,1,92.24,Winter,0,165
14,2022-01-01,S001,P0015,Toys,North,119,55,74,14.39,5,Snowy,0,13.59,Winter,0,64
15,2022-01-01,S001,P0016,Groceries,North,103,78,372,38.79,10,Snowy,0,35.14,Winter,0,115
16,2022-01-01,S001,P0017,Toys,North,128,59,0,21.21,0,Snowy,0,22.73,Winter,0,75
17,2022-01-01,S001,P0018,Groceries,North,281,78,0,54.40,5,Snowy,0,54.10,Winter,0,66
18,2022-01-01,S001,P0019,Furniture,North,281,61,0,95.56,10,Snowy,0,103.05,Winter,0,58
19,2022-01-01,S001,P0020,Furniture,North,266,36,0,100.47,5,Snowy,0,115.24,Winter,0,43

In [20]:
##### データ型の確認 #####
print(df.dtypes)

Date                      str
Store ID                  str
Product ID                str
Category                  str
Region                    str
Inventory Level         int64
Units Sold              int64
Units Ordered           int64
Price                 float64
Discount                int64
Weather Condition         str
Promotion               int64
Competitor Pricing    float64
Seasonality               str
Epidemic                int64
Demand                  int64
dtype: object

In [22]:
##### 'Grocerios'に絞ってdfを再度作成する #####
df_groceries = df[df['Category'] == 'Groceries'].copy()
df_groceries.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59
6,2022-01-01,S001,P0007,Groceries,North,118,81,335,23.27,5,Snowy,0,24.78,Winter,0,94
11,2022-01-01,S001,P0012,Groceries,North,289,121,215,84.48,0,Snowy,0,92.02,Winter,0,104
13,2022-01-01,S001,P0014,Groceries,North,252,121,479,80.13,10,Snowy,1,92.24,Winter,0,165
15,2022-01-01,S001,P0016,Groceries,North,103,78,372,38.79,10,Snowy,0,35.14,Winter,0,115

In [23]:
##### データ数の確認 #####
print(df_groceries.shape)

(30400, 16)

In [24]:
##### データ型の変換 #####
df_groceries['Date'] = pd.to_datetime(df_grocerios['Date'])

In [25]:
##### StoreIDとDateIDが同一なレコードを集計する #####
df_groceries = (
    df_groceries.groupby(['Date', 'StoreID'], as_index=False)
    .agg({
        'Inventory Level': 'sum',
        'Units Sold': 'sum',
        'Units Ordered': 'sum',

    })
)
#### どのカラムまでを'sum'するかは、データの内容をもって判断する必要があるので、次に実施する際にはここから ###

KeyError: 'StoreID'